name: fitness
publish_to: 'none'
description: A demo project for SpriteWidget.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  spritewidget:
    path: ../../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/jumpingjack.json
    - assets/jumpingjack.png