name: spritewidget
description: SpriteWidget is an open source toolkit for building complex, high performance animations and 2D games with Flutter.
version: 0.9.24

homepage: https://spritewidget.com/
repository: https://github.com/spritewidget/spritewidget/
issue_tracker: https://github.com/spritewidget/spritewidget/issues

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.6.3 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0