name: weather
description: A demo for SpriteWidget.
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  spritewidget:
      path: ../../
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/clouds-0.png
    - assets/clouds-1.png
    - assets/icon-rain.png
    - assets/icon-snow.png
    - assets/icon-sun.png
    - assets/ray.png
    - assets/sun.png
    - assets/weathersprites.json
    - assets/weathersprites.png