name: particledesigner
publish_to: 'none'
description: A demo for SpriteWidget.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_colorpicker: ^1.0.3
  spritewidget:
    path: ../../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/particle-0.png
    - assets/particle-1.png
    - assets/particle-2.png
    - assets/particle-3.png
    - assets/particle-4.png
    - assets/particle-5.png